"""empty message

Revision ID: c904ce80ba81
Revises: db56391690fd
Create Date: 2023-07-11 16:09:10.119635

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c904ce80ba81'
down_revision = 'db56391690fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('plan_amt')
        batch_op.drop_column('start_date')
        batch_op.drop_column('end_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('plan_amt', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('status', mysql.ENUM('pending', 'failed', 'paid'), server_default=sa.text("'pending'"), nullable=False))

    # ### end Alembic commands ###
